// <auto-generated />
using System;
using EFDDBF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFDDBF.Migrations
{
    [DbContext(typeof(EmployeeMgmtContext))]
    partial class EmployeeMgmtContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFDDBF.Models.Dept", b =>
                {
                    b.Property<int>("Deptno")
                        .HasColumnType("int")
                        .HasColumnName("deptno");

                    b.Property<string>("Dname")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("dname");

                    b.HasKey("Deptno")
                        .HasName("PK_dept");

                    b.ToTable("Dept", (string)null);
                });

            modelBuilder.Entity("EFDDBF.Models.Empm", b =>
                {
                    b.Property<int>("Deptno")
                        .HasColumnType("int")
                        .HasColumnName("deptno");

                    b.Property<string>("Addr")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("addr");

                    b.Property<int?>("Empno")
                        .HasColumnType("int")
                        .HasColumnName("empno");

                    b.Property<string>("Ename")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("ename");

                    b.HasKey("Deptno")
                        .HasName("PK_EMP");

                    b.ToTable("Empm", (string)null);
                });

            modelBuilder.Entity("EFDDBF.Models.Empm", b =>
                {
                    b.HasOne("EFDDBF.Models.Dept", "DeptnoNavigation")
                        .WithOne("Empm")
                        .HasForeignKey("EFDDBF.Models.Empm", "Deptno")
                        .IsRequired()
                        .HasConstraintName("FK_emp");

                    b.Navigation("DeptnoNavigation");
                });

            modelBuilder.Entity("EFDDBF.Models.Dept", b =>
                {
                    b.Navigation("Empm");
                });
#pragma warning restore 612, 618
        }
    }
}
